# Generated by Django 5.2.1 on 2025-06-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feaventador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarsModel',
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
