# Generated by Django 5.2.1 on 2025-06-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=100, verbose_name='Genel Ayar Adı')),
                ('bannerImage', models.FileField(blank=True, help_text='Logo varsa resmini yükleyiniz yoksa boş bırakabilirsiniz.', null=True, upload_to='images', verbose_name='Logo')),
                ('bannerText', models.CharField(blank=True, help_text='Firma adını logo yerine kullanabilirsiniz. (Örnek: KatmanKod)', max_length=50, null=True, verbose_name='Logo Yazı')),
                ('address', models.CharField(blank=True, help_text='İş yerinin mevcut adresi varsa giriniz.', max_length=250, null=True, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, help_text='İş yerinin mevcut telefon numarası varsa giriniz.', max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('phone2', models.CharField(blank=True, help_text='İş yerinin mevcut dahili hattı varsa giriniz.', max_length=20, null=True, verbose_name='Telefon Numarası 2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=50, verbose_name='Slider Adı')),
                ('imageDesktop', models.FileField(blank=True, help_text='Masaüstü Slider Resmi', null=True, upload_to='images', verbose_name='Masaüstü Slider')),
                ('imageMobile', models.FileField(blank=True, help_text='Mobil Slider Resmi', null=True, upload_to='images', verbose_name='Mobil Slider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(help_text='Hangi sosyal medya alanını eklediğinizin adını giriniz. (Örnek: Twitter)', max_length=50, verbose_name='Sosyal Medya Adı')),
                ('link', models.SlugField(help_text='Sosyal medya adresinizin linkini giriniz.', verbose_name='Sosyal Medya Linki')),
                ('icon', models.CharField(choices=[('T', '<i class="ri-twitter-x-fill"></i>'), ('F', '<i class="ri-facebook-fill"></i>'), ('L', '<i class="ri-linkedin-fill"></i>'), ('W', '<i class="ri-whatsapp-fill"></i>')], help_text='Eklediğiniz sosyal medyaya göre bir icon seçiniz.', max_length=1, verbose_name='Sosyal Medya İconu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='menumodel',
            name='bannerImage',
        ),
        migrations.RemoveField(
            model_name='menumodel',
            name='bannerText',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='addFooter',
            field=models.BooleanField(default=False, help_text='Sayfanın footer kısmında menüyü göstermek isterseniz tik koyunuz istemezseniz ellemeyiniz.', verbose_name="Footer'e Ekle"),
        ),
    ]
